import type {
  Candidate,
  Hypothesis,
  MarketIndex,
  SchemaTable,
  SimulatedTrade,
  StrategyMetric,
  WorkflowTask,
} from "../types";

export const today = "2026-06-20";

export const marketIndexes: MarketIndex[] = [
  { symbol: "TAIEX", name: "台股加權", value: 23484, changePct: 0.82, tone: "up" },
  { symbol: "NASDAQ", name: "那斯達克", value: 21831, changePct: 0.47, tone: "up" },
  { symbol: "SOX", name: "費半", value: 6042, changePct: 1.18, tone: "up" },
  { symbol: "VIX", name: "波動率", value: 15.9, changePct: -3.1, tone: "down" },
  { symbol: "USD/TWD", name: "美元台幣", value: 30.86, changePct: -0.12, tone: "flat" },
];

export const candidates: Candidate[] = [
  {
    id: "tw-ai-server",
    market: "TW",
    ticker: "AI-SRV",
    name: "AI 伺服器供應鏈籃子",
    theme: "AI 伺服器",
    catalyst: "月營收年增擴大，資料中心資本支出維持高檔",
    price: 312.5,
    volumeRatio: 1.72,
    technicalSignal: "突破 20 日高點",
    expectedHorizon: "1-5 日",
    setupScore: 84,
  },
  {
    id: "tw-cooling",
    market: "TW",
    ticker: "COOL",
    name: "散熱模組觀察",
    theme: "液冷散熱",
    catalyst: "高功耗 GPU 伺服器出貨題材延續",
    price: 186,
    volumeRatio: 1.31,
    technicalSignal: "量縮整理後放量",
    expectedHorizon: "3-10 日",
    setupScore: 77,
  },
  {
    id: "us-power",
    market: "US",
    ticker: "PWR-AI",
    name: "資料中心電力組合",
    theme: "電力基礎建設",
    catalyst: "AI 資料中心併網需求推升訂單能見度",
    price: 94.8,
    volumeRatio: 1.45,
    technicalSignal: "站回 50 日線",
    expectedHorizon: "5-20 日",
    setupScore: 73,
  },
  {
    id: "us-cyber",
    market: "US",
    ticker: "SEC-AI",
    name: "AI 資安軟體",
    theme: "雲端資安",
    catalyst: "企業 AI 導入提高資料治理與資安支出",
    price: 142.4,
    volumeRatio: 0.96,
    technicalSignal: "季線附近轉強",
    expectedHorizon: "10-20 日",
    setupScore: 68,
  },
  {
    id: "tw-dividend-bank",
    market: "TW",
    ticker: "DIV-FIN",
    name: "高股息金融觀察",
    theme: "現金流",
    catalyst: "配息預期穩定，資金防守輪動",
    price: 27.9,
    volumeRatio: 1.08,
    technicalSignal: "低波動箱型上緣",
    expectedHorizon: "10-30 日",
    setupScore: 61,
  },
];

export const initialHypotheses: Hypothesis[] = [
  {
    id: "hyp-001",
    date: today,
    market: "TW",
    ticker: "AI-SRV",
    name: "AI 伺服器供應鏈籃子",
    strategyId: "S-AI-MOM",
    theme: "AI 伺服器",
    signalSource: "月營收 + 技術突破",
    thesis: "若強營收個股突破 20 日高點且成交量大於近 20 日均量 1.5 倍，3 日內續漲機率提高。",
    direction: "bullish",
    horizonDays: 3,
    confidence: 72,
    entryRule: "收盤站上 20 日高點且量比 > 1.5",
    exitRule: "3 日內達 +4% 或失去強勢排行",
    stopRule: "跌破突破 K 低點或 -2.5%",
    status: "watching",
  },
  {
    id: "hyp-002",
    date: today,
    market: "US",
    ticker: "PWR-AI",
    name: "資料中心電力組合",
    strategyId: "S-EVENT-DRIFT",
    theme: "資料中心電力",
    signalSource: "產業新聞 + 族群輪動",
    thesis: "若 AI 電力題材在美股開盤後前 90 分鐘守住 VWAP，5 日內有事件延續行情。",
    direction: "bullish",
    horizonDays: 5,
    confidence: 64,
    entryRule: "開盤 90 分鐘後仍在 VWAP 上方",
    exitRule: "觸及 +5% 或題材熱度降溫",
    stopRule: "跌破 VWAP 並收不回",
    status: "triggered",
    actualReturnPct: 1.1,
  },
  {
    id: "hyp-003",
    date: today,
    market: "TW",
    ticker: "DIV-FIN",
    name: "高股息金融觀察",
    strategyId: "S-DIV-ROT",
    theme: "高股息防守",
    signalSource: "資金輪動",
    thesis: "若科技股急漲後轉震盪，高股息金融在低波動箱型上緣突破可能吸引防守資金。",
    direction: "neutral",
    horizonDays: 10,
    confidence: 56,
    entryRule: "突破箱型上緣且量能溫和放大",
    exitRule: "殖利率題材降溫或跌回箱型",
    stopRule: "跌破 20 日線",
    status: "watching",
  },
];

export const strategies: StrategyMetric[] = [
  {
    strategyId: "S-AI-MOM",
    name: "AI 強勢突破",
    marketScope: "台股 / 美股",
    theme: "AI、半導體、伺服器",
    horizon: "短線",
    version: "v0.3",
    sampleSize: 42,
    wins: 26,
    avgGainPct: 4.7,
    avgLossPct: 2.2,
    maxDrawdownPct: 5.6,
    falseSignalRate: 0.19,
    active: true,
  },
  {
    strategyId: "S-EVENT-DRIFT",
    name: "事件延續漂移",
    marketScope: "美股",
    theme: "財報、政策、資本支出",
    horizon: "短線",
    version: "v0.2",
    sampleSize: 31,
    wins: 17,
    avgGainPct: 5.4,
    avgLossPct: 2.8,
    maxDrawdownPct: 7.9,
    falseSignalRate: 0.24,
    active: true,
  },
  {
    strategyId: "S-DIV-ROT",
    name: "高股息輪動",
    marketScope: "台股",
    theme: "高股息、金融、防守資金",
    horizon: "長線",
    version: "v0.1",
    sampleSize: 18,
    wins: 11,
    avgGainPct: 2.1,
    avgLossPct: 1.4,
    maxDrawdownPct: 2.9,
    falseSignalRate: 0.16,
    active: false,
  },
  {
    strategyId: "S-REVERSAL",
    name: "急跌反彈",
    marketScope: "台股 / 美股",
    theme: "價值、錯殺、均值回歸",
    horizon: "波段",
    version: "v0.1",
    sampleSize: 23,
    wins: 10,
    avgGainPct: 3.8,
    avgLossPct: 3.1,
    maxDrawdownPct: 8.4,
    falseSignalRate: 0.31,
    active: false,
  },
  {
    strategyId: "S-LONG-AI",
    name: "AI 核心長線趨勢",
    marketScope: "台股 / 美股",
    theme: "長線核心科技、AI、雲端、資料中心",
    horizon: "長線",
    version: "v0.1",
    sampleSize: 12,
    wins: 8,
    avgGainPct: 18.5,
    avgLossPct: 7.4,
    maxDrawdownPct: 13.2,
    falseSignalRate: 0.18,
    active: true,
  },
  {
    strategyId: "S-CASHFLOW",
    name: "現金流核心配置",
    marketScope: "台股 / 美股",
    theme: "高股息現金流、金融、股息 ETF",
    horizon: "長線",
    version: "v0.1",
    sampleSize: 16,
    wins: 10,
    avgGainPct: 7.2,
    avgLossPct: 3.8,
    maxDrawdownPct: 6.1,
    falseSignalRate: 0.12,
    active: true,
  },
];

export const initialTrades: SimulatedTrade[] = [
  {
    id: "trade-001",
    date: today,
    market: "TW",
    ticker: "AI-SRV",
    name: "AI 伺服器供應鏈籃子",
    strategyId: "S-AI-MOM",
    side: "long",
    entryPrice: 312.5,
    targetPrice: 325,
    stopPrice: 304.7,
    plannedRiskPct: 0.95,
    status: "open",
    note: "突破後先以模擬倉追蹤 3 日。",
  },
  {
    id: "trade-002",
    date: today,
    market: "US",
    ticker: "PWR-AI",
    name: "資料中心電力組合",
    strategyId: "S-EVENT-DRIFT",
    side: "long",
    entryPrice: 94.8,
    targetPrice: 99.5,
    stopPrice: 91.9,
    plannedRiskPct: 0.75,
    status: "target",
    resultPct: 3.4,
    note: "事件漂移成立，等待樣本累積。",
  },
];

export const workflowTasks: WorkflowTask[] = [
  { id: "pre-1", phase: "盤前", label: "更新台股、美股、費半、VIX、匯率與期貨方向" },
  { id: "pre-2", phase: "盤前", label: "產生候選清單，排除量能不足與消息不明標的" },
  { id: "pre-3", phase: "盤前", label: "建立今日 3-10 個可驗證假設，寫清進出場條件" },
  { id: "live-1", phase: "盤中", label: "只在觸發條件成立時建立模擬交易" },
  { id: "live-2", phase: "盤中", label: "監控停損、目標、族群強弱與錯誤訊號" },
  { id: "post-1", phase: "盤後", label: "標記每個假設成立、失敗、過期或繼續觀察" },
  { id: "post-2", phase: "盤後", label: "寫下錯誤原因：資訊、時機、價格、紀律或市場狀態" },
  { id: "week-1", phase: "週檢討", label: "策略樣本滿 30 筆後才考慮升級，低期望值策略降級" },
];

export const schemaTables: SchemaTable[] = [
  {
    name: "market_sessions",
    purpose: "每日市場狀態與跨市場風向",
    fields: [
      { name: "session_date", type: "date", purpose: "交易日" },
      { name: "market", type: "text", purpose: "TW、US 或 global" },
      { name: "regime", type: "text", purpose: "多頭、空頭、盤整、事件行情" },
      { name: "index_snapshot_json", type: "json", purpose: "TAIEX、NASDAQ、SOX、VIX 等快照" },
      { name: "notes", type: "text", purpose: "盤前與盤後摘要" },
    ],
  },
  {
    name: "signals",
    purpose: "所有消息、技術、籌碼、財報與題材訊號",
    fields: [
      { name: "signal_id", type: "uuid", purpose: "訊號唯一 ID" },
      { name: "source_type", type: "text", purpose: "news、filing、technical、flow、manual" },
      { name: "ticker", type: "text", purpose: "標的代號" },
      { name: "theme", type: "text", purpose: "AI、半導體、高股息等分類" },
      { name: "observed_at", type: "datetime", purpose: "訊號出現時間" },
      { name: "strength_score", type: "integer", purpose: "0-100 訊號強度" },
    ],
  },
  {
    name: "hypotheses",
    purpose: "每日假設測試主表",
    fields: [
      { name: "hypothesis_id", type: "uuid", purpose: "假設 ID" },
      { name: "strategy_id", type: "text", purpose: "關聯策略版本" },
      { name: "ticker", type: "text", purpose: "測試標的" },
      { name: "thesis", type: "text", purpose: "可驗證論點" },
      { name: "entry_rule", type: "text", purpose: "觸發條件" },
      { name: "exit_rule", type: "text", purpose: "獲利或時間出場" },
      { name: "stop_rule", type: "text", purpose: "錯誤撤退條件" },
      { name: "actual_return_pct", type: "numeric", purpose: "驗證後結果" },
      { name: "status", type: "text", purpose: "watching、triggered、won、lost、expired" },
    ],
  },
  {
    name: "strategy_versions",
    purpose: "策略版本、樣本與升降級規則",
    fields: [
      { name: "strategy_id", type: "text", purpose: "策略 ID" },
      { name: "version", type: "text", purpose: "版本號" },
      { name: "rule_json", type: "json", purpose: "策略條件設定" },
      { name: "sample_size", type: "integer", purpose: "已驗證樣本數" },
      { name: "expectancy_pct", type: "numeric", purpose: "單次期望值" },
      { name: "score", type: "integer", purpose: "策略總分 0-100" },
    ],
  },
  {
    name: "simulated_trades",
    purpose: "紙上交易與真實交易前驗證",
    fields: [
      { name: "trade_id", type: "uuid", purpose: "交易 ID" },
      { name: "hypothesis_id", type: "uuid", purpose: "對應假設" },
      { name: "entry_price", type: "numeric", purpose: "進場價" },
      { name: "target_price", type: "numeric", purpose: "目標價" },
      { name: "stop_price", type: "numeric", purpose: "停損價" },
      { name: "planned_risk_pct", type: "numeric", purpose: "總資金風險比例" },
      { name: "result_pct", type: "numeric", purpose: "出場結果" },
    ],
  },
  {
    name: "intelligence_sources",
    purpose: "新聞、影片、公告與手動情報來源",
    fields: [
      { name: "source_id", type: "uuid", purpose: "來源 ID" },
      { name: "source_type", type: "text", purpose: "news、video、filing、manual_note" },
      { name: "reliability", type: "integer", purpose: "來源可信度 1-5" },
      { name: "horizon_type", type: "text", purpose: "short、swing、long" },
      { name: "tickers_json", type: "json", purpose: "可能影響標的" },
      { name: "raw_text", type: "text", purpose: "原始內容或逐字稿摘要" },
    ],
  },
  {
    name: "source_outcomes",
    purpose: "來源轉成假設後的驗證結果",
    fields: [
      { name: "outcome_id", type: "uuid", purpose: "驗證結果 ID" },
      { name: "source_id", type: "uuid", purpose: "關聯情報來源" },
      { name: "hypothesis_id", type: "uuid", purpose: "關聯假設" },
      { name: "result_status", type: "text", purpose: "pending、won、lost、expired" },
      { name: "actual_return_pct", type: "numeric", purpose: "市場反應結果" },
      { name: "source_score_delta", type: "numeric", purpose: "來源可靠度調整值" },
    ],
  },
];
